## Basic Array Construction and Properties

**Objectives**  

* creating basic array objects

* indexing arrays

* slicing

* changing the array shape

* matrix transform

* stacking arrays

* converting an array to a list

* special arrays (identity, zero, one, diagonal)


Always make sure numpy is imported

In [1]:
import numpy as np

### Creating Array Objects

Note: numpy has both **array** objects (strictly speaking, **ndarray** for multidimensional array) 
and **matrix** objects. The latter are strictly two-dimensional arrays and specialized in linear
algebra functions. Somewhat confusing, a one-dimensional **array** can have an Nx1, 1xN or N dimension.
On the other hand, a matrix is always two-dimensional. The main difference between the two (apart from the fact that
an array is more general) is that matrix operations are element-by-element for arrays and 
special commands (like **dot**) are needed for proper linear algebra operations. For a matrix
object it is the other way around. We will mostly be using **array** objects.

Create a simple one-dimensional array using the **arange** command (an extension of the **range** command for lists) to have a sequence of values

In [2]:
alist = range(5)  # creates a list of integers starting with 0 and going to 4

In [3]:
alist

range(0, 5)

In [4]:
a = np.arange(5)  # creates an array of integers starting with 0 and going to 4

In [5]:
a

array([0, 1, 2, 3, 4])

Check the data type of the array -- arrays are homogenous objects, use the **dtype** attribute

In [6]:
a.dtype

dtype('int32')

Note -- numpy prefix may not be necessary since pylab imports numpy -- however, we will always be stating it explicitly (good practice not to assume anything)

In [7]:
b = np.arange(5)

In [8]:
b

array([0, 1, 2, 3, 4])

Check the **shape** of the array

In [9]:
b.shape

(5,)

Note how this is a one-dimensional array, neither a row nor a column vector. In order to make it such,
we need to explicitly set the shape to specify the two dimensions.

Create a multidimensional array by passing **a list of arrays** to the array function

In [11]:
c = np.array([np.arange(3),np.arange(3)])

In [12]:
c

array([[0, 1, 2],
       [0, 1, 2]])

Note the double brackets.

In [13]:
c.shape

(2, 3)

Note: create a one-dimensional array by passing a list of same type objects to the array function

In [14]:
d = np.array( [1, 2, 3] )

In [15]:
d

array([1, 2, 3])

In [16]:
e = np.array( [4, 5, 6 ])

In [17]:
f = np.array( [d, e] )

In [18]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
f.shape

(2, 3)

In [20]:
g = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )    # note the double brackets

In [21]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
g.shape

(3, 4)

3-dimensional array: a list of lists of lists of one-dimensional arrays

In [23]:
h = np.array([ [ [1, 2, 3] , [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12]] ])

In [24]:
h

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
h.shape

(2, 2, 3)

<a name="index"/>

### Indexing

Selecting elements by indexing -- first index first, second index next (starts at 0)

In [26]:
g[0,0]

1

First index selects by row, so index 0 is first row

In [27]:
g[0]

array([1, 2, 3, 4])

Element in third row (2) and second column (1)

In [28]:
g[2,1]

10

First column, use : for the row index

In [29]:
g[:,0]

array([1, 5, 9])

Alternative indexing, use double brackets, or one bracket for each dimension

In [30]:
g[1][0]

5

Same idea to index elements from a multi-dimensional array, e.g., the three-dimensional array h

In [31]:
h[1,1,1]

11

In [32]:
h[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
h[1][1][:]

array([10, 11, 12])

### Slicing

Consider array g again

In [34]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Same principle as slicing lists, from first element to one before second index

Rows 1 (0) and 2 (1, i.e., one before 2), Column 2 (1)

In [35]:
g[0:2,1]

array([2, 6])

In [36]:
g1 = g[1,:]

In [37]:
g1

array([5, 6, 7, 8])

In [38]:
g1[-1]

8

In [39]:
g1[0:-1]

array([5, 6, 7])

Use third attribute for step size, e.g. from 0 to last (-1) by 2 steps

In [40]:
g1[0:-1:2]

array([5, 7])

Reverse the order of the array using step -1

In [41]:
g1[::-1]

array([8, 7, 6, 5])

### Array Shape

Use **reshape** to change the dimensions of an array

In [42]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
g.shape

(3, 4)

**reshape** works in place, does not actually change the object only the view of the object

In [44]:
g.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:

g.shape

(3, 4)

Alternative, use **resize** 

In [46]:
g.resize(4,3)

In [47]:
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
g.shape

(4, 3)

Both of these are useful to make the dimensions appropriate for calculations, but they are not permanent

Alternatively, change the shape by assigning **shape** to a tuple

In [49]:
g.shape = (3,4)

In [50]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
g.shape

(3, 4)

Assign reshaped array to a new object and it has the right shape

In [52]:
gg = g.reshape(4,3)

In [53]:
gg.shape

(4, 3)

In [54]:
gg

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Change two-dimensional array to a vector, row by row using **flatten**

In [55]:
gg.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
gg.shape

(4, 3)

Alternative is **ravel**

In [57]:
gg.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
gg.shape

(4, 3)

Need to assign to an new array object to make shape permanent

In [59]:
gg1 = gg.flatten()

In [60]:
gg1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
gg1.shape

(12,)

### Transpose of a matrix

Use **transpose( )** or **T**. This is useful to get the dimensions right
in calculations, but it is not permanent.

In [62]:
gg.shape

(4, 3)

In [63]:
gg.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [64]:
gg.shape

(4, 3)

In [65]:
gg.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [66]:
gg.T.shape

(3, 4)

Need to assign to a new object to make permanent

In [67]:
gg3 = gg.T

In [68]:
gg3

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [69]:
gg3.shape

(3, 4)

### Stacking Arrays

Horizontal stacking, i.e., column-wise, using **hstack**

In [70]:
a1 = np.array( [[1 , 2], [3, 4]])

In [71]:
a1

array([[1, 2],
       [3, 4]])

In [72]:
a2 = np.array( [[5, 6], [7, 8]])

In [73]:
a2

array([[5, 6],
       [7, 8]])

Note the double parens in **hstack**, one for the function, one for the tuple

In [74]:
aa = np.hstack((a1, a2))

In [75]:
aa

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Vertical stacking, i.e., row-wise using **vstack**

In [76]:
ab = np.vstack((a1,a2))

In [77]:
ab

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
ab.shape

(4, 2)

Vertical stacking is the same as **concatenate** with the default option

In [79]:
ac = np.concatenate((a1,a2))

In [80]:
ac

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [81]:
ac.shape

(4, 2)

**concatenate** takes a second argument, **axis**: axis = 0 is by row, axis = 1 is by column

In [82]:
ad = np.concatenate((a1,a2),axis=1)

In [83]:
ad

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Converting an array to a list

This is useful for creating a print out of the contents of an array

In [84]:
vv = ad.tolist()

In [85]:
vv

[[1, 2, 5, 6], [3, 4, 7, 8]]

In [88]:
for i in vv:
    print(i)

[1, 2, 5, 6]
[3, 4, 7, 8]


In [89]:
for i in range(len(vv)):
    for j in range(len(vv[i])):
        print(vv[i][j])

1
2
5
6
3
4
7
8


### Special Arrays

**Identity** Matrix (**eye**)

In [90]:
x = np.eye(4)

In [91]:
x

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [92]:
x.shape

(4, 4)

Matrix of **zeros**

In [93]:
y = np.zeros(4)

In [94]:
y

array([ 0.,  0.,  0.,  0.])

In [95]:
y.shape

(4,)

Note the double parens

In [96]:
yy = np.zeros((4,2))

In [97]:
yy

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [98]:
yy.shape

(4, 2)

Matrix of **ones**

In [99]:
z = np.ones(4)

In [100]:
z

array([ 1.,  1.,  1.,  1.])

In [101]:
zz = np.ones((4,2))

In [102]:
zz

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Creating a diagonal matrix using the **diag** command

In [103]:
xa = np.array([ 1, 2, 3, 4])

In [104]:
xa

array([1, 2, 3, 4])

In [105]:
zxa = np.diag(xa)

In [106]:
zxa

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

###Assignment 1

Carry out this assignment and record it in an iPython notebook. You have to post the 
notebook on the blackboard site by Thursday 1/24 5pm. It will be graded.

* create an arbitrary 4 by 4 matrix, say v

* extract the 2 by 2 matrix in the center

* turn this 2 by 2 matrix into an one-dimensional array and use it to construct a diagonal matrix

* create a listing (one item per line) of the individual elements on the diagonal (of the diagonal matrix)

* extract the lower-most diagonal element

* extract the last column of v and turn it into a row vector

* change the dimensions of v to 2 by 8

* create a 20 element array of consecutive integer values starting with 0

* convert the array into two matrices, one of dimension 4 by 5 and one of dimension 5 by 4

* initialize a zero matrix of dimension 3 by 3 and put the values 1, 2, 3 in the third column